### ISSUE TITLE
Upgrade Rails version 7.0.5.1 

### ISSUE THREAD

**Issue by kasugaijin** [kasugaijin/baja-pet-rescue#167]
Upgrade includes security fix for `redirect_to` which is used a lot in this application. 
See [release notes](https://rubyonrails.org/2023/6/26/Rails-Versions-7-0-5-1-6-1-7-4-have-been-released)

Ruby 3.1.x is still the recommended Ruby version per [this table](https://www.fastruby.io/blog/ruby/rails/versions/compatibility-table.html)

**Comment by Eduardo06sp** [comment]
I think it's important to make sure that important aspects of the app are tested when upgrading.

Are there any important tests missing for the app? I personally did not find any upon a quick review.

If you are comfortable with the current test coverage, I would like to be assigned to this issue. Otherwise, I think any missing tests should be addressed first.

**Comment by kasugaijin** [comment]
Yes upgrades are something to do carefully. This is a patch upgrade, so it should be a backwards compatible fix and I suspect not going to cause issues. I think the test suite is robust enough to catch any major issues.
